### ISSUE TITLE
GetMember withResults doesn't work anymore

### ISSUE THREAD

**Issue by Fllorent0D** [gfrenoy/TabT-API#15]
The API is not sending members results anymore. Don't know where to report the issue so I'm opening one here.

**Comment by gfrenoy** [comment]
This place is fine to report issues :)  You may try the [Mastodon](https://babelut.be/@tabt) account as well.

Now, I ran my standard unit tests and I don't see anything wrong ...

Can you give an example of what is not working for you ?

**Comment by Fllorent0D** [comment]
When you do a simple GetMember for my profile UniqueIndex=142453 and WithResults = true. You don’t get any data

**Comment by gfrenoy** [comment]
Oh I see ; some temporary results table were corrupted for season 2018-2019 (but working fine for the previous seasons)... Should be fixed now.  Thanks for the heads up.

**Comment by Fllorent0D** [comment]
Thanks for the quick fix :)
