### ISSUE TITLE
PHP Fatal error:  Call to undefined function create_division_title_text() 

### ISSUE THREAD

**Issue by oprichnik** [gfrenoy/TabT-API#17]
Après avoir installé l'application en local en suivant le INSTALL.md avec succès: je n'arrive pas à récupérer les équipes d'un club:

`PHP Fatal error:  Call to undefined function create_division_title_text() in /var/www/tabt/tabtapi.php on line 238`

Je ne vois en effet nul part dans le code l'inclusion du fichier "helpers.php".
En ajoutant un require de fichier, je récupère alors correctement les équipes.

Y a t-il un bug quelque part ?

PS: En testant d'autres calls sur l'API je constate que certains fichiers ne se trouvent pas dans le repository:

- public/calendar_fct.php
- public/classement_fct.php

**Comment by gfrenoy** [comment]
Hi Mallory.  What is published here is not yet fully functional but little by little ; I hope we can bring out all features in this public repository.

The the "helpers" issue ; feel free to submit a PR.

For the other includes ; we'll need to create them and then I can put the missing functions in it.

Thanks for your help !
