### ISSUE TITLE
CORS issue with AFTT/VTTL

### ISSUE THREAD

**Issue by Fllorent0D** [gfrenoy/TabT-API#18]
HI, 

I'm facing a CORS issue with my app. It's not working for a few days it seems. I see that `header('Access-Control-Allow-Origin: *');` is set correctly. Maybe something is wrong with the Apache server. 
I created a simple demo of my issue (https://stackblitz.com/edit/http-basics-fztxxv).

Can you please check? I have a lot of people coming back to me, asking me why it's not working anymore.

**Comment by gfrenoy** [comment]
ModPageSpeed is apparently removing the headers set by the apache2 code.  Not sure why but I've disabled ModPageSpeed for the API ; it's useless, anyway.

**Comment by Fllorent0D** [comment]
Thanks a lot! It's working fine 😊
