### ISSUE TITLE
Add parameter to force the language

### ISSUE THREAD

**Issue by Fllorent0D** [gfrenoy/TabT-API#3]
Is it possible a attribute in the Credentials (or elsewhere) to force the language of the response?

**Comment by gfrenoy** [comment]
Nope.  The language is given by the user profile.  So if you want to see answers in a different language, just change it in your profile on the TabT website (see bottom of the left menu once you are connected).

**Comment by Fllorent0D** [comment]
Already saw that but my app doesn't use user accounts. I would use them if I could register users and setup there accounts through the api.

**Comment by gfrenoy** [comment]
If you don't use Credentials, then the language is enforced by the TabT website itself... (and each federation has its preferred language).

That being said, this is how it works today.  If this does not fit your use, feel free to submit a PR ; don't think it would be too difficult to do...

**Comment by Fllorent0D** [comment]
Didn't know that each website has a preferred language. I will redirect each user to the good wsdl and it will be enough. 
If I have time, I will integrate that kind of endpoint in a PR 😊 

Thanks!

**Comment by gfrenoy** [comment]
Np.  Thanks for asking, I made this clearer in the documentation : https://github.com/gfrenoy/TabT-API/commit/465000b0f352b410da49a7b0a7c052ee7f40ffd5
